# Generated by Django 3.2.6 on 2021-08-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0003_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserAccount',
        ),
    ]
